version: '3.8'

services:
  postgres:
    container_name: postgres_container
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /opt/postgres
    volumes:
       - ${POSTGRES_PATH:-./db/postgres}:/opt/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    # pgadmin: